# frozen_string_literal: true

EuEinvoice::Semantic::En16931::GROUPS = [
  EuEinvoice::GroupDefinition.new('BG-2', :document, nil, nil, '1..1'),
  EuEinvoice::GroupDefinition.new('BG-1', :note, :notes, nil, '0..n'),
  EuEinvoice::GroupDefinition.new('BG-25', :line, :lines, nil, '1..n'),
  EuEinvoice::GroupDefinition.new('BG-31', :product, :product, 'BG-25', '1..1'),
  EuEinvoice::GroupDefinition.new('BG-32', :product_attribute, :attributes, 'BG-31', '0..n'),
  EuEinvoice::GroupDefinition.new('BG-29', :line, nil, 'BG-25', '1..1'),
  EuEinvoice::GroupDefinition.new('BG-30', :tax_breakdown, :tax, 'BG-25', '1..1'),
  EuEinvoice::GroupDefinition.new('BG-26', :period, :period, 'BG-25', '0..1'),
  EuEinvoice::GroupDefinition.new('BG-27', :allowance_charge, :allowances, 'BG-25', '0..n'),
  EuEinvoice::GroupDefinition.new('BG-27-0', :allowance_charge, nil, 'BG-27', '0..1'),
  EuEinvoice::GroupDefinition.new('BG-27-1', :allowance_charge, nil, 'BG-27', '1..1'),
  EuEinvoice::GroupDefinition.new('BG-28', :allowance_charge, :charges, 'BG-25', '0..n'),
  EuEinvoice::GroupDefinition.new('BG-28-0', :allowance_charge, nil, 'BG-28', '0..1'),
  EuEinvoice::GroupDefinition.new('BG-28-1', :allowance_charge, nil, 'BG-28', '1..1'),
  EuEinvoice::GroupDefinition.new('BG-4', :party, :seller, nil, '1..1'),
  EuEinvoice::GroupDefinition.new('BG-6', :contact, :contact, 'BG-4', '0..1'),
  EuEinvoice::GroupDefinition.new('BG-5', :address, :address, 'BG-4', '1..1'),
  EuEinvoice::GroupDefinition.new('BG-7', :party, :buyer, nil, '1..1'),
  EuEinvoice::GroupDefinition.new('BG-9', :contact, :contact, 'BG-7', '0..1'),
  EuEinvoice::GroupDefinition.new('BG-8', :address, :address, 'BG-7', '1..1'),
  EuEinvoice::GroupDefinition.new('BG-11', :party, :tax_representative, nil, '0..1'),
  EuEinvoice::GroupDefinition.new('BG-12', :address, :address, 'BG-11', '1..1'),
  EuEinvoice::GroupDefinition.new('BG-24', :supporting_document, :supporting_documents, nil, '0..n'),
  EuEinvoice::GroupDefinition.new('BG-13-00', :delivery, :delivery, nil, '0..1'),
  EuEinvoice::GroupDefinition.new('BG-13', :party, :party, 'BG-13-00', '0..1'),
  EuEinvoice::GroupDefinition.new('BG-15', :address, :address, 'BG-13', '0..1'),
  EuEinvoice::GroupDefinition.new('BG-19', :document, nil, nil, '0..1'),
  EuEinvoice::GroupDefinition.new('BG-10', :party, :payee, nil, '0..1'),
  EuEinvoice::GroupDefinition.new('BG-16', :payment_instructions, :payment, nil, '0..1'),
  EuEinvoice::GroupDefinition.new('BG-18', :payment_card, :payment_card, 'BG-16', '0..1'),
  EuEinvoice::GroupDefinition.new('BG-17', :credit_transfer, :credit_transfers, 'BG-16', '0..n'),
  EuEinvoice::GroupDefinition.new('BG-23', :tax_breakdown, :tax_breakdowns, nil, '1..n'),
  EuEinvoice::GroupDefinition.new('BG-14', :period, :billing_period, nil, '0..1'),
  EuEinvoice::GroupDefinition.new('BG-20', :allowance_charge, :allowances, nil, '0..n'),
  EuEinvoice::GroupDefinition.new('BG-20-0', :allowance_charge, nil, 'BG-20', '0..1'),
  EuEinvoice::GroupDefinition.new('BG-20-1', :allowance_charge, nil, 'BG-20', '1..1'),
  EuEinvoice::GroupDefinition.new('BG-21', :allowance_charge, :charges, nil, '0..n'),
  EuEinvoice::GroupDefinition.new('BG-21-0', :allowance_charge, nil, 'BG-21', '0..1'),
  EuEinvoice::GroupDefinition.new('BG-21-1', :allowance_charge, nil, 'BG-21', '1..1'),
  EuEinvoice::GroupDefinition.new('BG-22', :totals, :totals, nil, '1..1'),
  EuEinvoice::GroupDefinition.new('BG-3', :document_reference, :preceding_invoices, nil, '0..n')
].freeze
